-- =============================================================
--  schema.sql
--  NYC Yellow Taxi - January 2019
--  Database: PostgreSQL (Aiven)
--  Run: psql $DATABASE_URL -f db/schema.sql
-- =============================================================


-- Drop tables in reverse dependency order so re-running this
-- script on a fresh setup never fails on "table already exists".
DROP TABLE IF EXISTS trips          CASCADE;
DROP TABLE IF EXISTS zones          CASCADE;
DROP TABLE IF EXISTS vendors        CASCADE;
DROP TABLE IF EXISTS rate_codes     CASCADE;
DROP TABLE IF EXISTS payment_types  CASCADE;


-- -------------------------------------------------------------
-- 1. zones
--    Source: taxi_zone_lookup.csv (263 valid rows after
--    excluding LocationID 264 "Unknown" and 265 "Outside NYC")
--
--    Why a separate table?
--    PULocationID and DOLocationID appear on every one of the
--    7.28M trip rows. Without this table we would repeat the
--    borough and zone name 7.28M times. Storing them once here
--    and referencing by ID is the core normalization principle.
-- -------------------------------------------------------------
CREATE TABLE zones (
    location_id   SMALLINT     PRIMARY KEY,   -- 1–263, matches TLC lookup
    borough       VARCHAR(50)  NOT NULL,
    zone          VARCHAR(100) NOT NULL,
    service_zone  VARCHAR(50)  NOT NULL
);


-- -------------------------------------------------------------
-- 2. vendors
--    Source: TLC documentation (VendorID 1 = CMT, 2 = VeriFone)
--
--    Why a separate table?
--    VendorID is just a number in the raw data. This table turns
--    it into a human-readable name so the frontend and API
--    responses make sense without extra translation logic.
-- -------------------------------------------------------------
CREATE TABLE vendors (
    vendor_id    SMALLINT    PRIMARY KEY,   -- 1 or 2
    vendor_name  VARCHAR(100) NOT NULL
);


-- -------------------------------------------------------------
-- 3. rate_codes
--    Source: TLC documentation (RatecodeID 1–6)
--
--    Why a separate table?
--    Same reason as vendors. "JFK rate" is more meaningful than
--    "2". Also makes it easy to filter trips by rate type in
--    the frontend without hardcoding magic numbers everywhere.
-- -------------------------------------------------------------
CREATE TABLE rate_codes (
    rate_code_id    SMALLINT    PRIMARY KEY,   -- 1–6
    rate_code_name  VARCHAR(100) NOT NULL
);


-- -------------------------------------------------------------
-- 4. payment_types
--    Source: TLC documentation (payment_type 1–6)
--
--    Why a separate table?
--    Tip percentage analysis only makes sense for credit card
--    payments (type 1). Having this as a lookup table makes
--    that filter explicit and queryable by name, not by number.
-- -------------------------------------------------------------
CREATE TABLE payment_types (
    payment_type_id    SMALLINT    PRIMARY KEY,   -- 1–6
    payment_type_name  VARCHAR(50) NOT NULL
);


-- -------------------------------------------------------------
-- 5. trips  (the fact table — 7.28 M rows)
--    Source: trips_clean.csv produced by clean.py
--
--    Why this structure?
--    All four lookup tables above are referenced as foreign keys
--    here. The derived feature columns from Step 7 of the
--    cleaning pipeline are stored directly so the API never has
--    to recompute them on every query.
--
--    Column notes:
--    - trip_id          : surrogate PK, auto-generated by the DB
--    - store_and_fwd_flag: already converted to bool by clean.py
--    - tip_percentage   : NULL for non-card payments by design
--    - total_reconciles : boolean QA flag, rows are never dropped
--                         just because this is FALSE
-- -------------------------------------------------------------
CREATE TABLE trips (

    -- Primary key
    trip_id                  BIGSERIAL    PRIMARY KEY,

    -- Foreign keys to lookup tables
    vendor_id                SMALLINT     NOT NULL REFERENCES vendors(vendor_id),
    rate_code_id             SMALLINT     NOT NULL REFERENCES rate_codes(rate_code_id),
    pu_location_id           SMALLINT     NOT NULL REFERENCES zones(location_id),
    do_location_id           SMALLINT     NOT NULL REFERENCES zones(location_id),
    payment_type_id          SMALLINT     NOT NULL REFERENCES payment_types(payment_type_id),

    -- Timestamps
    pickup_datetime          TIMESTAMP    NOT NULL,
    dropoff_datetime         TIMESTAMP    NOT NULL,

    -- Trip metrics (raw)
    passenger_count          SMALLINT     NOT NULL,
    trip_distance            REAL         NOT NULL,

    -- Fare breakdown (raw)
    fare_amount              NUMERIC(8,2) NOT NULL,
    extra                    NUMERIC(8,2) NOT NULL,
    mta_tax                  NUMERIC(8,2) NOT NULL,
    tip_amount               NUMERIC(8,2) NOT NULL,
    tolls_amount             NUMERIC(8,2) NOT NULL,
    improvement_surcharge    NUMERIC(8,2) NOT NULL,
    congestion_surcharge     NUMERIC(8,2) NOT NULL DEFAULT 0.00,
    total_amount             NUMERIC(8,2) NOT NULL,

    -- Operational flag
    store_and_fwd_flag       BOOLEAN      NOT NULL,

    -- Derived features (engineered by clean.py Step 7)
    trip_duration_seconds    INTEGER      NOT NULL,
    trip_duration_min        REAL         NOT NULL,
    avg_speed_mph            REAL         NOT NULL,
    pickup_hour              SMALLINT     NOT NULL,   -- 0–23
    pickup_dow               SMALLINT     NOT NULL,   -- 0=Mon, 6=Sun
    fare_per_mile            REAL,                    -- NULL if distance = 0 edge case
    is_airport_trip          BOOLEAN      NOT NULL,
    tip_percentage           REAL,                    -- NULL for non-card payments
    total_reconciles         BOOLEAN      NOT NULL

);


-- =============================================================
--  INDEXES
--  We index the columns that the API and frontend will filter
--  or group by most often. Without indexes, every query on
--  7.28M rows does a full table scan, which is very slow.
-- =============================================================

-- Time-based queries (rush hour patterns, daily trends)
CREATE INDEX idx_trips_pickup_datetime  ON trips (pickup_datetime);
CREATE INDEX idx_trips_pickup_hour      ON trips (pickup_hour);
CREATE INDEX idx_trips_pickup_dow       ON trips (pickup_dow);

-- Zone-based queries (busiest pickup/dropoff zones)
CREATE INDEX idx_trips_pu_location      ON trips (pu_location_id);
CREATE INDEX idx_trips_do_location      ON trips (do_location_id);

-- Payment and fare analysis
CREATE INDEX idx_trips_payment_type     ON trips (payment_type_id);

-- Airport trip segmentation
CREATE INDEX idx_trips_airport          ON trips (is_airport_trip);