-- =============================================================
--  seed_lookups.sql
--  Populates the four small lookup/dimension tables.
--  Must be run AFTER schema.sql and BEFORE load_trips.py
--  because trips rows reference these as foreign keys.
--
--  Run: psql $DATABASE_URL -f db/seed_lookups.sql
-- =============================================================


-- -------------------------------------------------------------
--  1. vendors
--     Source: TLC Trip Record User Guide
--     VendorID 1 = Creative Mobile Technologies (CMT)
--     VendorID 2 = VeriFone Inc.
-- -------------------------------------------------------------
INSERT INTO vendors (vendor_id, vendor_name) VALUES
    (1, 'Creative Mobile Technologies (CMT)'),
    (2, 'VeriFone Inc.');


-- -------------------------------------------------------------
--  2. rate_codes
--     Source: TLC Trip Record User Guide
--     RatecodeID 1–6 are the only documented valid values.
--     Your teammate's clean.py already dropped the 252 rows
--     with RatecodeID = 99 (undocumented), so every trip row
--     in trips_clean.csv will match one of these 6 values.
-- -------------------------------------------------------------
INSERT INTO rate_codes (rate_code_id, rate_code_name) VALUES
    (1, 'Standard rate'),
    (2, 'JFK'),
    (3, 'Newark'),
    (4, 'Nassau or Westchester'),
    (5, 'Negotiated fare'),
    (6, 'Group ride');


-- -------------------------------------------------------------
--  3. payment_types
--     Source: TLC Trip Record User Guide
--     payment_type 1–6 are the only documented valid values.
--     Note: tip_percentage in trips is NULL for types 2–6
--     because cash tips are not recorded by the meter.
-- -------------------------------------------------------------
INSERT INTO payment_types (payment_type_id, payment_type_name) VALUES
    (1, 'Credit card'),
    (2, 'Cash'),
    (3, 'No charge'),
    (4, 'Dispute'),
    (5, 'Unknown'),
    (6, 'Voided trip');


-- -------------------------------------------------------------
--  4. zones
--     Source: taxi_zone_lookup.csv (263 valid rows)
--     LocationID 264 (Unknown) and 265 (Outside NYC) were
--     excluded by your teammate's clean.py Step 5, so we
--     do not insert them here — any trip referencing them
--     was already dropped before this point.
-- -------------------------------------------------------------
INSERT INTO zones (location_id, borough, zone, service_zone) VALUES
    (1,   'EWR',           'Newark Airport',                    'EWR'),
    (2,   'Queens',        'Jamaica Bay',                       'Boro Zone'),
    (3,   'Bronx',         'Allerton/Pelham Gardens',           'Boro Zone'),
    (4,   'Manhattan',     'Alphabet City',                     'Yellow Zone'),
    (5,   'Staten Island', 'Arden Heights',                     'Boro Zone'),
    (6,   'Staten Island', 'Arrochar/Fort Wadsworth',           'Boro Zone'),
    (7,   'Queens',        'Astoria',                           'Boro Zone'),
    (8,   'Queens',        'Astoria Park',                      'Boro Zone'),
    (9,   'Queens',        'Auburndale',                        'Boro Zone'),
    (10,  'Queens',        'Baisley Park',                      'Boro Zone'),
    (11,  'Brooklyn',      'Bath Beach',                        'Boro Zone'),
    (12,  'Manhattan',     'Battery Park',                      'Yellow Zone'),
    (13,  'Manhattan',     'Battery Park City',                 'Yellow Zone'),
    (14,  'Brooklyn',      'Bay Ridge',                         'Boro Zone'),
    (15,  'Queens',        'Bay Terrace/Fort Totten',           'Boro Zone'),
    (16,  'Queens',        'Bayside',                           'Boro Zone'),
    (17,  'Brooklyn',      'Bedford',                           'Boro Zone'),
    (18,  'Bronx',         'Bedford Park',                      'Boro Zone'),
    (19,  'Queens',        'Bellerose',                         'Boro Zone'),
    (20,  'Bronx',         'Belmont',                           'Boro Zone'),
    (21,  'Brooklyn',      'Bensonhurst East',                  'Boro Zone'),
    (22,  'Brooklyn',      'Bensonhurst West',                  'Boro Zone'),
    (23,  'Staten Island', 'Berkeley Gardens/Elm Park',         'Boro Zone'),
    (24,  'Brooklyn',      'Boerum Hill',                       'Boro Zone'),
    (25,  'Brooklyn',      'Borough Park',                      'Boro Zone'),
    (26,  'Bronx',         'Bronx Park',                        'Boro Zone'),
    (27,  'Bronx',         'Bronxdale',                         'Boro Zone'),
    (28,  'Brooklyn',      'Brooklyn Heights',                  'Boro Zone'),
    (29,  'Brooklyn',      'Brooklyn Navy Yard',                'Boro Zone'),
    (30,  'Brooklyn',      'Brownsville',                       'Boro Zone'),
    (31,  'Brooklyn',      'Bushwick North',                    'Boro Zone'),
    (32,  'Brooklyn',      'Bushwick South',                    'Boro Zone'),
    (33,  'Queens',        'cambria Heights',                   'Boro Zone'),
    (34,  'Manhattan',     'Canal Street',                      'Yellow Zone'),
    (35,  'Brooklyn',      'Canarsie',                          'Boro Zone'),
    (36,  'Brooklyn',      'Carroll Gardens',                   'Boro Zone'),
    (37,  'Manhattan',     'Central Harlem',                    'Boro Zone'),
    (38,  'Manhattan',     'Central Harlem North',              'Boro Zone'),
    (39,  'Manhattan',     'Central Park',                      'Yellow Zone'),
    (40,  'Staten Island', 'Charleston/Tottenville',            'Boro Zone'),
    (41,  'Manhattan',     'Chinatown',                         'Yellow Zone'),
    (42,  'Bronx',         'City Island',                       'Boro Zone'),
    (43,  'Bronx',         'Claremont/Bathgate',                'Boro Zone'),
    (44,  'Manhattan',     'Clinton East',                      'Yellow Zone'),
    (45,  'Brooklyn',      'Clinton Hill',                      'Boro Zone'),
    (46,  'Manhattan',     'Clinton West',                      'Yellow Zone'),
    (47,  'Bronx',         'Co-Op City',                        'Boro Zone'),
    (48,  'Manhattan',     'Cobble Hill',                       'Boro Zone'),
    (49,  'Queens',        'College Point',                     'Boro Zone'),
    (50,  'Brooklyn',      'Columbia Street',                   'Boro Zone'),
    (51,  'Brooklyn',      'Coney Island',                      'Boro Zone'),
    (52,  'Queens',        'Corona',                            'Boro Zone'),
    (53,  'Queens',        'Corona',                            'Boro Zone'),
    (54,  'Brooklyn',      'Crown Heights North',               'Boro Zone'),
    (55,  'Brooklyn',      'Crown Heights South',               'Boro Zone'),
    (56,  'Brooklyn',      'Cypress Hills',                     'Boro Zone'),
    (57,  'Queens',        'Douglaston',                        'Boro Zone'),
    (58,  'Brooklyn',      'Downtown Brooklyn/MetroTech',       'Boro Zone'),
    (59,  'Bronx',         'Dreier-Offerman/Sunset Park West',  'Boro Zone'),
    (60,  'Brooklyn',      'Dumbo/Vinegar Hill',                'Boro Zone'),
    (61,  'Brooklyn',      'Dyker Heights',                     'Boro Zone'),
    (62,  'Manhattan',     'East Chelsea',                      'Yellow Zone'),
    (63,  'Bronx',         'East Concourse/Concourse Village',  'Boro Zone'),
    (64,  'Queens',        'East Elmhurst',                     'Boro Zone'),
    (65,  'Brooklyn',      'East Flatbush/Farragut',            'Boro Zone'),
    (66,  'Brooklyn',      'East Flatbush/remsen Village',      'Boro Zone'),
    (67,  'Queens',        'East Flushing',                     'Boro Zone'),
    (68,  'Manhattan',     'East Harlem North',                 'Boro Zone'),
    (69,  'Manhattan',     'East Harlem South',                 'Boro Zone'),
    (70,  'Brooklyn',      'East New York',                     'Boro Zone'),
    (71,  'Brooklyn',      'East New York/Pennsylvania Avenue', 'Boro Zone'),
    (72,  'Bronx',         'East Tremont',                      'Boro Zone'),
    (73,  'Manhattan',     'East Village',                      'Yellow Zone'),
    (74,  'Brooklyn',      'East Williamsburg',                 'Boro Zone'),
    (75,  'Bronx',         'Eastchester',                       'Boro Zone'),
    (76,  'Queens',        'Elmhurst',                          'Boro Zone'),
    (77,  'Queens',        'Elmhurst/Maspeth',                  'Boro Zone'),
    (78,  'Staten Island', 'Eltingville/Annadale/Prince''s Bay','Boro Zone'),
    (79,  'Brooklyn',      'Erasmus',                           'Boro Zone'),
    (80,  'Queens',        'Far Rockaway',                      'Boro Zone'),
    (81,  'Manhattan',     'Financial District North',          'Yellow Zone'),
    (82,  'Manhattan',     'Financial District South',          'Yellow Zone'),
    (83,  'Brooklyn',      'Flatbush/Ditmas Park',              'Boro Zone'),
    (84,  'Manhattan',     'Flatlands',                         'Boro Zone'),
    (85,  'Brooklyn',      'Flatlands',                         'Boro Zone'),
    (86,  'Queens',        'Flushing',                          'Boro Zone'),
    (87,  'Queens',        'Flushing Meadows-Corona Park',      'Boro Zone'),
    (88,  'Bronx',         'Fordham South',                     'Boro Zone'),
    (89,  'Queens',        'Forest Hills',                      'Boro Zone'),
    (90,  'Queens',        'Forest Park/Highland Park',         'Boro Zone'),
    (91,  'Brooklyn',      'Fort Greene',                       'Boro Zone'),
    (92,  'Queens',        'Fresh Meadows',                     'Boro Zone'),
    (93,  'Staten Island', 'Freshkills Park',                   'Boro Zone'),
    (94,  'Manhattan',     'Garment District',                  'Yellow Zone'),
    (95,  'Queens',        'Glen Oaks',                         'Boro Zone'),
    (96,  'Queens',        'Glendale',                          'Boro Zone'),
    (97,  'Manhattan',     'Governor''s Island/Ellis Island/Liberty Island', 'Yellow Zone'),
    (98,  'Manhattan',     'Governor''s Island/Ellis Island/Liberty Island', 'Yellow Zone'),
    (99,  'Manhattan',     'Governor''s Island/Ellis Island/Liberty Island', 'Yellow Zone'),
    (100, 'Queens',        'Howard Beach',                      'Boro Zone'),
    (101, 'Manhattan',     'Gramercy',                          'Yellow Zone'),
    (102, 'Brooklyn',      'Gravesend',                         'Boro Zone'),
    (103, 'Staten Island', 'Great Kills',                       'Boro Zone'),
    (104, 'Staten Island', 'Great Kills Park',                  'Boro Zone'),
    (105, 'Brooklyn',      'Green-Wood Cemetery',               'Boro Zone'),
    (106, 'Brooklyn',      'Greenpoint',                        'Boro Zone'),
    (107, 'Manhattan',     'Greenwich Village North',           'Yellow Zone'),
    (108, 'Manhattan',     'Greenwich Village South',           'Yellow Zone'),
    (109, 'Staten Island', 'Grymes Hill/Clifton',               'Boro Zone'),
    (110, 'Manhattan',     'Hamilton Heights',                  'Boro Zone'),
    (111, 'Queens',        'Hammels/Arverne',                   'Boro Zone'),
    (112, 'Staten Island', 'Heartland Village/Todt Hill',       'Boro Zone'),
    (113, 'Bronx',         'Highbridge',                        'Boro Zone'),
    (114, 'Manhattan',     'Highbridge Park',                   'Boro Zone'),
    (115, 'Queens',        'Hillcrest/Pomonok',                 'Boro Zone'),
    (116, 'Queens',        'Hollis',                            'Boro Zone'),
    (117, 'Brooklyn',      'Homecrest',                         'Boro Zone'),
    (118, 'Queens',        'Howard Beach',                      'Boro Zone'),
    (119, 'Manhattan',     'Hudson Sq',                         'Yellow Zone'),
    (120, 'Bronx',         'Hunts Point',                       'Boro Zone'),
    (121, 'Manhattan',     'Inwood',                            'Boro Zone'),
    (122, 'Manhattan',     'Inwood Hill Park',                  'Boro Zone'),
    (123, 'Queens',        'Jackson Heights',                   'Boro Zone'),
    (124, 'Queens',        'Jamaica',                           'Boro Zone'),
    (125, 'Queens',        'Jamaica Estates',                   'Boro Zone'),
    (126, 'Queens',        'JFK Airport',                       'Airports'),
    (127, 'Bronx',         'Kingsbridge Heights',               'Boro Zone'),
    (128, 'Manhattan',     'Kips Bay',                          'Yellow Zone'),
    (129, 'Queens',        'Kew Gardens',                       'Boro Zone'),
    (130, 'Queens',        'Kew Gardens Hills',                 'Boro Zone'),
    (131, 'Bronx',         'Laconia',                           'Boro Zone'),
    (132, 'Queens',        'LaGuardia Airport',                 'Airports'),
    (133, 'Brooklyn',      'Lenox Hill East',                   'Boro Zone'),
    (134, 'Manhattan',     'Lenox Hill East',                   'Yellow Zone'),
    (135, 'Manhattan',     'Lenox Hill West',                   'Yellow Zone'),
    (136, 'Manhattan',     'Lincoln Square East',               'Yellow Zone'),
    (137, 'Manhattan',     'Lincoln Square West',               'Yellow Zone'),
    (138, 'Manhattan',     'Little Italy/NoLiTa',               'Yellow Zone'),
    (139, 'Queens',        'Long Island City/Hunters Point',    'Boro Zone'),
    (140, 'Queens',        'Long Island City/Queens Plaza',     'Boro Zone'),
    (141, 'Bronx',         'Longwood',                          'Boro Zone'),
    (142, 'Manhattan',     'Lower East Side',                   'Yellow Zone'),
    (143, 'Brooklyn',      'Madison',                           'Boro Zone'),
    (144, 'Brooklyn',      'Manhattan Beach',                   'Boro Zone'),
    (145, 'Manhattan',     'Manhattan Valley',                  'Yellow Zone'),
    (146, 'Manhattan',     'Manhattanville',                    'Boro Zone'),
    (147, 'Manhattan',     'Marble Hill',                       'Boro Zone'),
    (148, 'Brooklyn',      'Marine Park/Floyd Bennett Field',   'Boro Zone'),
    (149, 'Brooklyn',      'Marine Park/Mill Basin',            'Boro Zone'),
    (150, 'Staten Island', 'Mariners Harbor',                   'Boro Zone'),
    (151, 'Queens',        'Maspeth',                           'Boro Zone'),
    (152, 'Manhattan',     'Meatpacking/West Village West',     'Yellow Zone'),
    (153, 'Bronx',         'Melrose South',                     'Boro Zone'),
    (154, 'Queens',        'Middle Village',                    'Boro Zone'),
    (155, 'Manhattan',     'Midtown Center',                    'Yellow Zone'),
    (156, 'Manhattan',     'Midtown East',                      'Yellow Zone'),
    (157, 'Manhattan',     'Midtown North',                     'Yellow Zone'),
    (158, 'Manhattan',     'Midtown South',                     'Yellow Zone'),
    (159, 'Brooklyn',      'Mill Basin',                        'Boro Zone'),
    (160, 'Staten Island', 'Mill Town/Bloomfield/Graniteville', 'Boro Zone'),
    (161, 'Manhattan',     'Morningside Heights',               'Boro Zone'),
    (162, 'Manhattan',     'Morningside Heights',               'Yellow Zone'),
    (163, 'Bronx',         'Morrisania/Melrose',                'Boro Zone'),
    (164, 'Bronx',         'Mott Haven/Port Morris',            'Boro Zone'),
    (165, 'Bronx',         'Mount Hope',                        'Boro Zone'),
    (166, 'Manhattan',     'Murray Hill',                       'Yellow Zone'),
    (167, 'Queens',        'Murray Hill-Queens',                'Boro Zone'),
    (168, 'Staten Island', 'New Dorp/Midland Beach',            'Boro Zone'),
    (169, 'Queens',        'North Corona',                      'Boro Zone'),
    (170, 'Bronx',         'Norwood',                           'Boro Zone'),
    (171, 'Queens',        'Oakland Gardens',                   'Boro Zone'),
    (172, 'Staten Island', 'Oakwood',                           'Boro Zone'),
    (173, 'Brooklyn',      'Ocean Hill',                        'Boro Zone'),
    (174, 'Brooklyn',      'Ocean Parkway South',               'Boro Zone'),
    (175, 'Queens',        'Old Astoria',                       'Boro Zone'),
    (176, 'Queens',        'Ozone Park',                        'Boro Zone'),
    (177, 'Brooklyn',      'Park Slope',                        'Boro Zone'),
    (178, 'Bronx',         'Parkchester',                       'Boro Zone'),
    (179, 'Bronx',         'Pelham Bay',                        'Boro Zone'),
    (180, 'Bronx',         'Pelham Bay Park',                   'Boro Zone'),
    (181, 'Bronx',         'Pelham Parkway',                    'Boro Zone'),
    (182, 'Manhattan',     'Penn Station/Madison Sq West',      'Yellow Zone'),
    (183, 'Queens',        'Peter Cooper Village',              'Boro Zone'),
    (184, 'Manhattan',     'Peter Cooper Village',              'Yellow Zone'),
    (185, 'Queens',        'Prospect-Lefferts Gardens',         'Boro Zone'),
    (186, 'Brooklyn',      'Prospect Heights',                  'Boro Zone'),
    (187, 'Brooklyn',      'Prospect Park',                     'Boro Zone'),
    (188, 'Queens',        'Queens Village',                    'Boro Zone'),
    (189, 'Queens',        'Queensboro Hill',                   'Boro Zone'),
    (190, 'Queens',        'Queensbridge/Ravenswood',           'Boro Zone'),
    (191, 'Manhattan',     'Randalls Island',                   'Yellow Zone'),
    (192, 'Brooklyn',      'Red Hook',                          'Boro Zone'),
    (193, 'Queens',        'Rego Park',                         'Boro Zone'),
    (194, 'Queens',        'Richmond Hill',                     'Boro Zone'),
    (195, 'Queens',        'Ridgewood',                         'Boro Zone'),
    (196, 'Bronx',         'Rikers Island',                     'Boro Zone'),
    (197, 'Bronx',         'Riverdale/North Riverdale/Fieldston', 'Boro Zone'),
    (198, 'Queens',        'Rockaway Park',                     'Boro Zone'),
    (199, 'Manhattan',     'Roosevelt Island',                  'Boro Zone'),
    (200, 'Queens',        'Rosedale',                          'Boro Zone'),
    (201, 'Staten Island', 'Rossville/Woodrow',                 'Boro Zone'),
    (202, 'Queens',        'Saint Albans',                      'Boro Zone'),
    (203, 'Staten Island', 'Seaside/Fort Wadsworth',            'Boro Zone'),
    (204, 'Queens',        'Sunnyside',                         'Boro Zone'),
    (205, 'Brooklyn',      'Sheepshead Bay',                    'Boro Zone'),
    (206, 'Manhattan',     'SoHo',                              'Yellow Zone'),
    (207, 'Brooklyn',      'South Beach/Dongan Hills',          'Boro Zone'),
    (208, 'Queens',        'South Jamaica',                     'Boro Zone'),
    (209, 'Queens',        'South Ozone Park',                  'Boro Zone'),
    (210, 'Brooklyn',      'South Williamsburg',                'Boro Zone'),
    (211, 'Queens',        'Springfield Gardens North',         'Boro Zone'),
    (212, 'Queens',        'Springfield Gardens South',         'Boro Zone'),
    (213, 'Staten Island', 'St. George/New Brighton',           'Boro Zone'),
    (214, 'Queens',        'Steinway',                          'Boro Zone'),
    (215, 'Manhattan',     'Stuy Town/Peter Cooper Village',    'Yellow Zone'),
    (216, 'Brooklyn',      'Stuyvesant Heights',                'Boro Zone'),
    (217, 'Queens',        'Sunnyside',                         'Boro Zone'),
    (218, 'Brooklyn',      'Sunset Park East',                  'Boro Zone'),
    (219, 'Brooklyn',      'Sunset Park West',                  'Boro Zone'),
    (220, 'Manhattan',     'Sutton Place/Turtle Bay North',     'Yellow Zone'),
    (221, 'Manhattan',     'Times Sq/Theatre District',         'Yellow Zone'),
    (222, 'Manhattan',     'TriBeCa/Civic Center',              'Yellow Zone'),
    (223, 'Manhattan',     'Two Bridges/Seward Park',           'Yellow Zone'),
    (224, 'Manhattan',     'UN/Turtle Bay South',               'Yellow Zone'),
    (225, 'Manhattan',     'Union Sq',                          'Yellow Zone'),
    (226, 'Bronx',         'University Heights/Morris Heights', 'Boro Zone'),
    (227, 'Manhattan',     'Upper East Side North',             'Yellow Zone'),
    (228, 'Manhattan',     'Upper East Side South',             'Yellow Zone'),
    (229, 'Manhattan',     'Upper West Side North',             'Yellow Zone'),
    (230, 'Manhattan',     'Upper West Side South',             'Yellow Zone'),
    (231, 'Bronx',         'Van Cortlandt Park',                'Boro Zone'),
    (232, 'Bronx',         'Van Cortlandt Village',             'Boro Zone'),
    (233, 'Bronx',         'Van Nest/Morris Park',              'Boro Zone'),
    (234, 'Manhattan',     'Washington Heights North',          'Boro Zone'),
    (235, 'Manhattan',     'Washington Heights South',          'Boro Zone'),
    (236, 'Manhattan',     'West Chelsea/Hudson Yards',         'Yellow Zone'),
    (237, 'Manhattan',     'West Village',                      'Yellow Zone'),
    (238, 'Bronx',         'Westchester Village/Unionport',     'Boro Zone'),
    (239, 'Manhattan',     'West Harlem',                       'Boro Zone'),
    (240, 'Queens',        'Whitestone',                        'Boro Zone'),
    (241, 'Queens',        'Willets Point',                     'Boro Zone'),
    (242, 'Bronx',         'Williamsbridge/Olinville',          'Boro Zone'),
    (243, 'Brooklyn',      'Williamsburg (North Side)',         'Boro Zone'),
    (244, 'Brooklyn',      'Williamsburg (South Side)',         'Boro Zone'),
    (245, 'Brooklyn',      'Windsor Terrace',                   'Boro Zone'),
    (246, 'Queens',        'Wood Haven',                        'Boro Zone'),
    (247, 'Bronx',         'Woodlawn/Webster Ave',              'Boro Zone'),
    (248, 'Queens',        'Woodside',                          'Boro Zone'),
    (249, 'Manhattan',     'World Trade Center',                'Yellow Zone'),
    (250, 'Manhattan',     'Yorkville East',                    'Yellow Zone'),
    (251, 'Manhattan',     'Yorkville West',                    'Yellow Zone'),
    (252, 'Brooklyn',      'Canarsie',                          'Boro Zone'),
    (253, 'Brooklyn',      'Crown Heights North',               'Boro Zone'),
    (254, 'Brooklyn',      'Flatbush/Ditmas Park',              'Boro Zone'),
    (255, 'Queens',        'Baisley Park',                      'Boro Zone'),
    (256, 'Queens',        'Jamaica',                           'Boro Zone'),
    (257, 'Brooklyn',      'Brownsville',                       'Boro Zone'),
    (258, 'Bronx',         'Soundview/Bruckner',                'Boro Zone'),
    (259, 'Bronx',         'Soundview/Castle Hill',             'Boro Zone'),
    (260, 'Bronx',         'Spuyten Duyvil/Kingsbridge',        'Boro Zone'),
    (261, 'Manhattan',     'South Harlem',                      'Boro Zone'),
    (262, 'Manhattan',     'Midtown East',                      'Yellow Zone'),
    (263, 'Manhattan',     'Newark Airport',                    'Airports');